network_scanning:
  interface: wlx00c0cab2f615
  hop_interval: 0.5
  enable_hopping: true
  channel: 6

channles:
  ch_2_4G: [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
  ch_5G: [36,40,44,48, 149,153,157,161,165]
